variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "fetch"
  GET_SOURCES_ATTEMPTS: "3"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules
  - .cache-loader

before_script:
  - yarn

stages:
  - lint
  - style
  - test
  - build
  - deploy

lint:
  script:
   - yarn run lint-parallel
  stage: lint

style:
  script:
   - yarn run style
  stage: style

test-backend:
  script:
   - yarn run test-back-setup
   - yarn run test-back
   - yarn run test-back-teardown
  stage: test
  when: always
  artifacts:
    paths:
      - coverage

build-frontend:
  script:
   - yarn run build
  stage: build
  when: always

build-frontend-prod:
  script:
   - yarn run build-prod
  only:
   - master
  stage: build

deploy:
  script:
   - MIDWAY_HOST=pa-terraformer01.terrain.int:3000 yarn run build-prod
   - cp -R ../Search /opt/Search/ && cd /opt/Search && killall yarn nodemon
   - NODE_ENV=production yarn start &
  only:
   - master
  stage: deploy
  tags:
    - shell
    - deploy
  when: manual
  environment:
    name: production
    url: http://pa-terraformer01.terrain.int:3000

