variables:
  GIT_SSL_NO_VERIFY: "true"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - yarn

stages:
  lint
  fix
  test-backend

lint:
  script:
   - yarn run lint
  stage: lint

fix:
  script:
   - yarn run fix
  stage: lint

test-backend:
  script:
   - yarn run test-back-all
  stage: test-backend
  artifacts:
    - coverage
