variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "clone"
  GET_SOURCES_ATTEMPTS: "3"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules

before_script:
  - yarn
  - ( cd sigint && yarn )
  - ( cd analytics.js && yarn )

stages:
  - lint
  - style
  - test-front
  - test-back
  - test-sigint
  - build
  - deploy
  - fullstack

lint:
  script:
   - yarn lint-parallel
  stage: lint

style:
  script:
   - yarn style
  stage: style

test-frontend:
  script:
   - yarn test-front
  stage: test-front
  when: always

test-backend:
  script:
   - yarn test-back-setup
   - yarn test-back
   - yarn test-back-teardown
  stage: test-back
  artifacts:
    paths:
      - coverage

test-sigint:
  script:
    - yarn test-sigint-setup
    - ( cd sigint && yarn test )
    - yarn test-sigint-teardown
  stage: test-sigint

build-frontend:
  script:
   - yarn build
  stage: build

build-analytics-js:
  script:
   - ( cd analytics.js && yarn build )
  stage: build

build-frontend-prod:
  script:
   - yarn build-prod
  only:
   - master
  stage: build

fullstack:
  script:
    - yarn clean
    - MIDWAY_HOST=`hostname`:3000 yarn build
    - yarn test-fullstack-setup
    - killall node || true;
    - NODE_ENV=production yarn start-midway > ./midwayConsole.log 2>&1&
    - sleep 20
    - yarn test-fullstack-component
    - yarn test-fullstack-login
    - yarn test-rr-builder
    - killall node || true;
    - yarn test-fullstack-teardown
  stage: fullstack
  allow_failure: true
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
    - rr/test/builder/__image_snapshots__/__diff_output__
    - rr/test/login/__image_snapshots__/__diff_output__
  after_script:
    - killall node || true;
    - ./midway/test/scripts/copy_screenshot.sh || true;

deploy:
  script:
   - MIDWAY_HOST=pa-terraformer01.terrain.int:33000 yarn build-prod
   - rsync -a --stats ../Search /opt --exclude '*.db' --exclude '.git'
   - fuser -k -n tcp 33000 || true
   - cd /opt/Search && NODE_ENV=production yarn start -- --port 33000 &
  only:
   - master
  stage: deploy
  tags:
    - shell
    - deploy
  when: manual
  environment:
    name: production
    url: http://pa-terraformer01.terrain.int:3000

