# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

variables:
  GIT_SSL_NO_VERIFY: "true"
  
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - terrain/moviesdb-elk:1.0a
  - terrain/moviesdb-mysql:1.0a
  - terrain/moviesdb-sqlite:1.0a

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - apt --assume-yes install parallel
  - yarn install

lint:
  script:
    - npm run lint

test_backends:
  script:
   - npm install
   - npm run fix
   - npm run test-back
