variables:
  GIT_SSL_NO_VERIFY: "true"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:

test_backends:
  script:
   - yarn
   - yarn run test-back-all

fix:
  script:
   - yarn run fix
