variables:
  GIT_SSL_NO_VERIFY: "true"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:

lint:
  script:
   - yarn run lint


test_backends:
  script:
   - yarn install
   - yarn run lint
   - yarn run style
   - stat moviesdb.db && ls -l moviesdb.db
   - yarn run test-back-all
