variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "clone"
  GET_SOURCES_ATTEMPTS: "3"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules

before_script:
  - yarn
  - ( cd sigint && yarn )
  - ( cd analytics.js && yarn )

stages:
  - lint
  - style
  - test-front
  - test-back
  - test-sigint
  - build
  - deploy

lint:
  script:
   - yarn run lint-parallel
  stage: lint

style:
  script:
   - yarn run style
  stage: style

test-frontend:
  script:
   - yarn run test-front
  stage: test-front
  when: always

test-backend:
  script:
   - yarn run test-back-setup
   - yarn run test-back
   - yarn run test-back-teardown
  stage: test-back
  when: always
  artifacts:
    paths:
      - coverage

test-sigint:
  script:
    - ( cd sigint && yarn run test )
  stage: test-sigint
  when: always

build-frontend:
  script:
   - yarn run build
  stage: build
  when: always

build-frontend-prod:
  script:
   - yarn run build-prod
  only:
   - master
  stage: build

deploy:
  script:
   - MIDWAY_HOST=pa-terraformer01.terrain.int:33000 yarn run build-prod
   - rsync -a --stats ../Search /opt --exclude '*.db' --exclude '.git'
   - fuser -k -n tcp 33000 || true
   - cd /opt/Search && NODE_ENV=production yarn start -- --port 33000 &
  only:
   - master
  stage: deploy
  tags:
    - shell
    - deploy
  when: manual
  environment:
    name: production
    url: http://pa-terraformer01.terrain.int:3000

