variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: "fetch"
  GET_SOURCES_ATTEMPTS: "3"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - yarn

stages:
  - lint
  - style
  - test

lint:
  script:
   - yarn run lint-parallel
  stage: lint

style:
  script:
   - yarn run style
  stage: style

test-backend:
  script:
   - yarn run test-back-setup
   - yarn run test-back
   - yarn run test-back-teardown
  stage: test
  when: always
  artifacts:
    paths:
      - coverage

test-frontend:
  script:
   - yarn run build
  stage: test
  when: always

test-frontend-prod:
  script:
   - yarn run build-prod
  only:
   - master
  stage: test

