trigger:
  - master
  - releases/*

pr:
  - master
  - releases/*

stages:
- stage: A
  jobs:
  - job: A1
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - script: |
          echo Hello, world!
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a one-line script'
