trigger:
  - master
  - releases/*

pr:
  - master
  - releases/*

variables:
  TZ: America/Los_Angeles

stages:
- stage: style_and_compilation
  jobs:
  - job: diff_style
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          yarn
          yarn add npm-run-all tslint typescript-formatter
          yarn commit-style
        displayName: 'diff_style'
  - job: lint
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          yarn
          yarn add npm-run-all tslint typescript-formatter
          yarn style
        displayName: 'lint'
  - job: build_analytics_js
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          cd analytics.js
          yarn
          yarn build
        displayName: 'Build analytics.js'
  - job: build_backend
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          yarn
          yarn build-server
        displayName: 'Build backend'
  - job: build_frontend
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          yarn
          yarn build
        displayName: 'Build frontend'
- stage: standard_tests
  jobs:
  - job: test_sigint
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          timeout 240 yarn test-sigint-setup
          cd sigint
          yarn
          yarn test
        displayName: 'Test SigInt'
  - job: test_frontend
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          yarn
          yarn test-front
        displayName: 'Test frontend'
  - job: test_backend
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          yarn
          timeout 240 yarn test-back-setup
          yarn test-back
        displayName: 'Test backend'
  - job: fullstack_meta
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
      - template: ci_templates/linux_setup.yml
      - script: |
          yarn
          timeout 240 yarn test-fullstack-setup
          yarn clean
          yarn build
          NODE_ENV=production nohup yarn start-midway-prod > ./midwayConsole.log < /dev/null 2>&1&
          sleep 25
          yarn test-fullstack-component
          cat ./midwayConsole.log
        displayName: 'Fullstack tests'
